[workspace]
name = "fundamentals-workshop"
version = "0.1.0"
authors = ["ejolly <eshin.jolly@gmail.com>"]
channels = ["ejolly", "conda-forge"]
platforms = ["osx-arm64", "osx-64"]
repository = "https://github.com/psyc-201/fundamentals-workshop/"

# Use pixi add someLibrary to install Python packages
# Use pixi add r-someLibrary to isntall R packages
# This file will be auto-updated for you!
[dependencies]
python = ">=3.11" 
pymer4 = ">=0.9.2"
ipykernel = ">=6.29.5,<7"
ruff = ">=0.12.2,<0.13"
jupyter = ">=1.1.1,<2"
quarto = ">=1.7.32,<2"
jupyter-cache = ">=1.0.1,<2"
seaborn = ">=0.13.2,<0.14"
r-skimr = ">=2.2.1,<3"
r-visdat = ">=0.6.0,<0.7"
r-dt = ">=0.34.0,<0.35"
r-tidyverse = ">=2.0.0,<3"
r-knitr = ">=1.50,<2"
r-languageserver = ">=0.3.16,<0.4"
r-rmarkdown = ">=2.29,<3"
r-irkernel = ">=1.3.2,<2"

# Tasks are shell commands we can call with pixi run myTask
# We include some that configure the environment for you when you
# use pixi run setup
[tasks]
setup = [
{ task = "init_profile" }, 
{ task = "setup_profile" }, 
{ task = "setup_ipython" }]

render = "quarto preview code/"

[tasks.preview]
args =["name"]
cmd = "quarto preview code/{{ name }}"

[tasks.convert]
args =["name"]
cmd = "quarto convert code/{{ name }}"

# --Python kernel setup sub-tasks--
[tasks.init_profile]
cmd = "mkdir .pixi/envs/default/etc/ipython && ipython profile create --ipython-dir=\"$(pwd)/.pixi/envs/default/etc/ipython/\""

[tasks.setup_profile]
cmd = "cp .ipython_config.py \"$(pwd)/.pixi/envs/default/etc/ipython/ipython_config.py\" && cp .ipython_kernel_config.py \"$(pwd)/.pixi/envs/default/etc/ipython/ipython_kernel_config.py\""

[tasks.setup_ipython]
cmd = "python -m ipykernel install --user --name=\"$(basename $(pwd))\" --display-name=\"$(basename $(pwd))\""

[tasks.kernels]
cmd = "jupyter kernelspec list"

# Python syntax-checking settings
[tool.ruff]
extend-include = ["*.ipynb", "*.qmd"]
[tool.ruff.lint]
ignore = ["W292", "E501", "E731", "E741", "F401", "E703"]
