project:
  title: "basics"
  type: website
  output-dir: _output
  render: 
    - "*.qmd"
    - "*.md"

engine: jupyter

format:
  html:
    toc: true
    toc-depth: 4
    theme: cosmo
    highlight-style: tango
    df-print: kable

execute: 
  cache: true
ipynb-shell-interactivity: all

website: 
  title: "Fundamentals Workshop"
  back-to-top-navigation: true
  repo-url: https://github.com/psyc-201/fundamentals-workshop
  repo-actions: [source, issue]
  page-footer: "2025, Eshin Jolly, Bria Long, Jane Yang"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "R basics"
        href: r-basics.qmd
      - text: "Python basics"
        href: python-basics.qmd
      - text: "Cheatsheets"
        href: cheatsheets.qmd


